language: node_js
node_js:
    - 10

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH="$HOME/.yarn/bin:$PATH"

cache:
    yarn: true

install:
    - yarn global add lerna
    - lerna bootstrap
    - lerna run build-deps --scope @r6db/desktop

script:
    - lerna run build --scope @r6db/desktop
